version: '3.8'

services:
  iptv-manager:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./downloads:/downloads
    networks:
      - iptv-network

networks:
  iptv-network:
    driver: bridge
